/* Auto-generated by genmsg_cpp for file /home/tao/software/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/Traj.msg */
#ifndef ORB_SLAM2_MESSAGE_TRAJ_H
#define ORB_SLAM2_MESSAGE_TRAJ_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Pose.h"

namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct Traj_ {
  typedef Traj_<ContainerAllocator> Type;

  Traj_()
  : header()
  , poses()
  , mnIds()
  {
  }

  Traj_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , poses(_alloc)
  , mnIds(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  poses;

  typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _mnIds_type;
  std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  mnIds;


  typedef boost::shared_ptr< ::ORB_SLAM2::Traj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::Traj_<ContainerAllocator>  const> ConstPtr;
}; // struct Traj
typedef  ::ORB_SLAM2::Traj_<std::allocator<void> > Traj;

typedef boost::shared_ptr< ::ORB_SLAM2::Traj> TrajPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::Traj const> TrajConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::Traj_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::Traj_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::Traj_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::Traj_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5880ce1007ffb54f9d4910dd5b0777b0";
  }

  static const char* value(const  ::ORB_SLAM2::Traj_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5880ce1007ffb54fULL;
  static const uint64_t static_value2 = 0x9d4910dd5b0777b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/Traj";
  }

  static const char* value(const  ::ORB_SLAM2::Traj_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
geometry_msgs/Pose[] poses\n\
uint32[] mnIds\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::Traj_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ORB_SLAM2::Traj_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ORB_SLAM2::Traj_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::Traj_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.poses);
    stream.next(m.mnIds);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Traj_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::Traj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::Traj_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "mnIds[]" << std::endl;
    for (size_t i = 0; i < v.mnIds.size(); ++i)
    {
      s << indent << "  mnIds[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.mnIds[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_TRAJ_H

